update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,11 +17,11 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Check directory structure
-        run: |
-          echo "Root directory:"
-          ls -la
-          echo "Contents of sms-service:"
-          ls -la ./sms-service
+              run: |
+                echo "Root directory:"
+                ls -la
+                echo "Contents of sms-service:"
+                ls -la ./sms-service || echo "sms-service directory not found"
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
